CREATE ROLE Administrator;
CREATE ROLE Visitor WITH LOGIN PASSWORD '228';


GRANT ALL PRIVILEGES ON DATABASE retail_analytics TO Administrator; 

-- ALTER ROLE Administrator WITH SUPERUSER;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO Administrator; 
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO Administrator; 
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO Administrator;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO Administrator; 


GRANT CONNECT ON DATABASE retail_analytics TO Visitor;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO Visitor;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO Visitor;



REASSIGN OWNED BY Administrator TO postgres;
DROP OWNED BY Administrator;
DROP ROLE Administrator;

REASSIGN OWNED BY Visitor TO postgres;
DROP OWNED BY Visitor;
DROP ROLE Visitor;


